### ISSUE TITLE
No firehose loader for Redmi Note 10 PRO (SWEET)

### ISSUE THREAD

**Issue by Zibri** [hoplik/Firehose-Finder#25]
This is the original but it requests AUTH.
[prog_ufs_firehose_sm7150_ddr.zip](https://github.com/hoplik/Firehose-Finder/files/9624055/prog_ufs_firehose_sm7150_ddr.zip)

**Comment by hoplik** [comment]
Thank you for your interest of the program. Unfortunately, there are no plans to support work with programmers with authorization.

**Comment by Zibri** [comment]
> Thank you for your interest of the program. Unfortunately, there are no plans to support work with programmers with authorization.

I tried to patch it removing the auth but then it does not start...

**Comment by hoplik** [comment]
All new programmers are digitally signed. There's a chain of three (usually) certificates. By changing the code in the program, you will not be able to run it, because the checksum will be violated.

**Comment by Zibri** [comment]
> All new programmers are digitally signed. There's a chain of three (usually) certificates. By changing the code in the program, you will not be able to run it, because the checksum will be violated.

Yep.. I noticed. So to flash a custom abl the chain should be broken before...

**Comment by hoplik** [comment]
Can you check this programmer on your device? From the chat, they ask to add it to the database. Does it require authorization or not? Pay attention to the SDL Version. Here it is already 3, not 2, like yours. Carefully, otherwise the rollback may fuse.
![image](https://user-images.githubusercontent.com/60131631/195201972-e652dccd-46d0-49c4-9ce4-8b652907bbe5.png)
[prog_ufs_firehose_sm7150_ddr_AN.zip](https://github.com/hoplik/Firehose-Finder/files/9759869/prog_ufs_firehose_sm7150_ddr_AN.zip)

**Comment by Userj96** [comment]
> Can you check this programmer on your device? From the chat, they ask to add it to the database. Does it require authorization or not? Pay attention to the SDL Version. Here it is already 3, not 2, like yours. Carefully, otherwise the rollback may fuse. ![image](https://user-images.githubusercontent.com/60131631/195201972-e652dccd-46d0-49c4-9ce4-8b652907bbe5.png) [prog_ufs_firehose_sm7150_ddr_AN.zip](https://github.com/hoplik/Firehose-Finder/files/9759869/prog_ufs_firehose_sm7150_ddr_AN.zip)

Bro pls break the chain 😭🤧🙏

**Comment by hoplik** [comment]
As I wrote earlier, firehose is signed by a certificate chain with a SHA256 encryption level. This means that changing the structure of the code will lead to a checksum error. Even if you correct this firehose correctly, you still won't be able to use it, because the hash of the root certificate is entered in the processor at production and checked against the hash of the firehose certificate.
