### ISSUE TITLE
Trying to get a CAT S62 Pro working

### ISSUE THREAD

**Issue by Cryonic90** [hoplik/Firehose-Finder#30]
I can't register myself for the 4pda forum (can't read russion, so the CAPTCHA is holding me back).
But I'm trying to get a firehose programmer file for this device.
This is the info I get from the tool:
Binary build date: Jun 25 2019 @ 03:16:15
QSAHARASERVER CALLED LIKE THIS: 'QSaharaServer.ex'Current working dir: C:\Users\devri\AppData\Local\Apps\2.0\OC3AX0XR.1KE\5J6X1E0G.0KB\fire..tion_0000000000000000_0017.0007_99d8235691d6815e
Sahara mappings:
2: amss.mbn
6: apps.mbn
8: dsp1.mbn
10: dbl.mbn
11: osbl.mbn
12: dsp2.mbn
16: efs1.mbn
17: efs2.mbn
20: efs3.mbn
21: sbl1.mbn
22: sbl2.mbn
23: rpm.mbn
25: tz.mbn
28: dsp3.mbn
29: acdb.mbn
30: wdt.mbn
31: mba.mbn

15:44:28: Sahara protocol completed

Done.
Received S/N CPU - 8F33A578
HWID - 0008C0E123243732
OEM_PK_HASH (64) - EE43AB11D0CA65C9DE6F717134DAF0819B9610FA36C5AD94A484520EB7708836
SBL SW Ver. - 00000000

Is there a possibility to revive this device?
Thanks in advance!

**Comment by hoplik** [comment]
Hi. I saw you received a fully detailed answer on the xda-developers forum. I have nothing to add to it. Thank you for using the FhF program, I have added your model IDs to the database, they will appear in the list at the next update. If you find a suitable firehose, please find an opportunity to test it with your connected device, so that when the test is successfully completed, this fire hose goes to the chat and I can add it to the database.
